### ISSUE TITLE
Wrong details about font size command

### ISSUE THREAD

**Issue by denismaier** [epfllibrary/latex-course#1]
There is an error on this page: https://epfllibrary.github.io/latex-course/03-Text/index.html

The font size commands are explained incorrectly. In short, font size commands aren't commands with arguments. They are switches and change the fontsize until the end of the current group. The given examples work by accident:

```
        \tiny{tiny}

        \small{small}

        \normalsize{normal}

        \large{large}

        \LARGE{LARGE}

        \Huge{Huge}
```
Here, every fontsize command is overwritten by the next. But this here won't work:

```
This is \Large{large}, and this should be normalsize again. (But it isn't.)
```

Correct usage is this:

```
This is {\Large large}, and this should be normalsize again. (And it is.)
```

More details [here](https://tex.stackexchange.com/a/7313/32018)

**Comment by railyards** [comment]
Thank you Denis for the feedback.
We'll update the course shortly.
Best,
Mathilde

**Comment by amasson84** [comment]
@denismaier thank you for this issue.
It is now corrected.
